#pragma once

// Structural controls (ADR-002): mount/unmount subtrees in response to state,
// without a whole-tree diff. IfNode mounts an optional child; ForEachNode
// generates a rebuildable list of children with a configurable layout direction.

#include <functional>
#include <memory>

#include "wui/node.h"
#include "wui/widgets.h"

namespace wui {

// Mounts a single optional child produced by a factory when visible.
class IfNode : public ContainerNode {
public:
    using Factory = std::function<std::unique_ptr<Node>()>;

    void setFactory(Factory factory);
    void setVisible(bool visible);
    [[nodiscard]] bool visible() const noexcept { return visible_; }

    [[nodiscard]] SizeF measure(const Constraints& constraints) const override;
    void layout(const RectF& bounds) override;

private:
    void reconcile();

    Factory factory_;
    bool visible_{false};
};

// Layout direction for ForEachNode.
enum class ForEachDirection {
    Vertical,   // Column-like (default)
    Horizontal, // Row-like
};

// A rebuildable list container whose children are (re)generated by the ForEach
// builder. Layout direction is configurable (vertical or horizontal), decoupled
// from a specific layout widget class.
class ForEachNode : public ContainerNode {
public:
    ForEachNode& direction(ForEachDirection dir) noexcept;
    void setDirection(ForEachDirection dir) noexcept;
    [[nodiscard]] ForEachDirection direction() const noexcept;

    ForEachNode& gap(float gap) noexcept;
    void setGap(float gap) noexcept;
    [[nodiscard]] float gap() const noexcept;

    ForEachNode& padding(InsetsF padding) noexcept;
    void setPadding(InsetsF padding) noexcept;
    [[nodiscard]] InsetsF padding() const noexcept;

    ForEachNode& align(Alignment align) noexcept;
    void setAlign(Alignment align) noexcept;
    [[nodiscard]] Alignment align() const noexcept;

    [[nodiscard]] SizeF measure(const Constraints& constraints) const override;
    void layout(const RectF& bounds) override;

private:
    ForEachDirection direction_{ForEachDirection::Vertical};
    float gap_{0.0f};
    InsetsF padding_{};
    Alignment align_{Alignment::Start};
};

} // namespace wui
