#include "wui/form_feedback.h"
#include <algorithm>
#include <cmath>
#include <utility>
#include "wui/text_input.h"
#include "wui/text_metrics.h"
#include "wui/theme.h"

namespace wui { namespace {
constexpr float kGap=4, kHGap=12, kPad=12, kIcon=20, kMsgGap=8, kActionW=72, kActionH=28;
float widthOf(const std::string& s,const TextStyleToken& t) noexcept { if(const auto* m=textMeasurer()) return m->measureText(s,t.size,t.weight).width; return s.size()*t.size*.56f; }
Color validation(FieldValidationState s,const Theme& t) noexcept { switch(s){case FieldValidationState::Warning:return t.colors.statusWarning;case FieldValidationState::Error:return t.colors.statusDanger;case FieldValidationState::Success:return t.colors.statusSuccess;default:return t.colors.neutralForeground3;} }
Color accent(MessageBarIntent i,const Theme& t) noexcept { switch(i){case MessageBarIntent::Success:return t.colors.statusSuccess;case MessageBarIntent::Warning:return t.colors.statusWarning;case MessageBarIntent::Error:return t.colors.statusDanger;default:return t.colors.statusInfo;} }
Color messageBg(MessageBarIntent i) noexcept { switch(i){case MessageBarIntent::Success:return {237,247,237,255};case MessageBarIntent::Warning:return {255,244,206,255};case MessageBarIntent::Error:return {253,237,238,255};default:return {239,246,252,255};} }
} // namespace

Field::Field(std::string v):label_(std::move(v)){}
Field& Field::label(std::string v){setLabel(std::move(v));return *this;} void Field::setLabel(std::string v){if(label_!=v){label_=std::move(v);syncControlSemantics();markDirty(DirtyFlag::Layout);}} const std::string& Field::label()const noexcept{return label_;}
Field& Field::hint(std::string v){setHint(std::move(v));return *this;} void Field::setHint(std::string v){if(hint_!=v){hint_=std::move(v);markDirty(DirtyFlag::Layout);}} const std::string& Field::hint()const noexcept{return hint_;}
Field& Field::validationMessage(std::string v){setValidationMessage(std::move(v));return *this;} void Field::setValidationMessage(std::string v){if(validationMessage_!=v){validationMessage_=std::move(v);syncControlSemantics();markDirty(DirtyFlag::Layout);}} const std::string& Field::validationMessage()const noexcept{return validationMessage_;}
Field& Field::validationState(FieldValidationState v)noexcept{setValidationState(v);return *this;} void Field::setValidationState(FieldValidationState v)noexcept{if(validationState_!=v){validationState_=v;syncControlSemantics();markDirty(DirtyFlag::Paint);}} FieldValidationState Field::validationState()const noexcept{return validationState_;}
Field& Field::required(bool v)noexcept{setRequired(v);return *this;} void Field::setRequired(bool v)noexcept{if(required_!=v){required_=v;markDirty(DirtyFlag::Paint);}} bool Field::isRequired()const noexcept{return required_;}
Field& Field::orientation(FieldOrientation v)noexcept{setOrientation(v);return *this;} void Field::setOrientation(FieldOrientation v)noexcept{if(orientation_!=v){orientation_=v;markDirty(DirtyFlag::Layout);}} FieldOrientation Field::orientation()const noexcept{return orientation_;}
Field& Field::enabled(bool v)noexcept{setEnabled(v);return *this;} void Field::setEnabled(bool v)noexcept{if(enabled_==v)return;enabled_=v;if(auto* n=control())if(auto* c=dynamic_cast<ControlNode*>(n))c->setEnabled(v);markDirty(DirtyFlag::Paint);} bool Field::isEnabled()const noexcept{return enabled_;}
Field& Field::control(std::unique_ptr<Node> v){setControl(std::move(v));return *this;} void Field::setControl(std::unique_ptr<Node> v){clearChildren();if(v)appendChild(std::move(v));syncControlSemantics();markDirty(DirtyFlag::Layout);} Node* Field::control()const noexcept{return children().empty()?nullptr:children().front().get();}
void Field::syncControlSemantics(){if(auto* i=dynamic_cast<TextInput*>(control())){if(!label_.empty())i->setAccessibleLabel(label_);i->setInvalid(validationState_==FieldValidationState::Error);i->setEnabled(enabled_);}else if(auto* c=dynamic_cast<ControlNode*>(control()))c->setEnabled(enabled_);} float Field::labelWidth()const noexcept{return widthOf(label_+(required_?" *":""),theme().typography.body1Strong);}
SizeF Field::measure(const Constraints& c)const{const auto&t=theme();auto* n=control();const SizeF cs=n?n->measureWithConstraints(c):SizeF{};const float lh=label_.empty()?0:t.typography.body1Strong.lineHeight,hh=hint_.empty()?0:t.typography.caption1.lineHeight,vh=validationMessage_.empty()?0:t.typography.caption1.lineHeight;if(orientation_==FieldOrientation::Horizontal){const float lw=label_.empty()?0:labelWidth()+kHGap;return c.clamp({lw+cs.width,std::max(lh,cs.height+(hh?kGap+hh:0)+(vh?kGap+vh:0))});}const float gaps=(lh&&cs.height?kGap:0)+(hh?kGap:0)+(vh?kGap:0);return c.clamp({std::max({labelWidth(),cs.width,widthOf(hint_,t.typography.caption1),widthOf(validationMessage_,t.typography.caption1)}),lh+cs.height+hh+vh+gaps});}
void Field::layout(const RectF& b){Node::layout(b);if(auto*n=control()){const auto&t=theme();const float lw=orientation_==FieldOrientation::Horizontal&&!label_.empty()?std::min(b.width,labelWidth()+kHGap):0;const float y=orientation_==FieldOrientation::Vertical&&!label_.empty()?b.y+t.typography.body1Strong.lineHeight+kGap:b.y;const SizeF s=n->measureWithConstraints({0,std::max(0.f,b.width-lw),0,b.height});n->layout({b.x+lw,y,std::max(0.f,b.width-lw),s.height});}clearLayoutDirtyRecursively();}
void Field::paint(PaintContext& c){const auto&t=theme();const auto&ls=t.typography.body1Strong;const auto&hs=t.typography.caption1;auto*n=control();const float lx=bounds().x,head=orientation_==FieldOrientation::Horizontal&&!label_.empty()?std::min(bounds().width,labelWidth()+kHGap):0;const Color fg=enabled_?t.colors.neutralForeground1:t.colors.neutralForegroundDisabled;if(!label_.empty()){RectF b{lx,bounds().y,head?head-kHGap:bounds().width,ls.lineHeight};c.drawText(label_,b.x,c.centeredTextBottom(label_,b,ls.size,ls.weight),ls.size,fg,ls.weight,ls.family);if(required_)c.drawText("*",b.x+widthOf(label_,ls)+t.spacing.horizontal.xs,c.centeredTextBottom("*",b,ls.size,ls.weight),ls.size,t.colors.statusDanger,ls.weight,ls.family);}float y=n?n->bounds().y+n->bounds().height:bounds().y;const float x=bounds().x+head,w=std::max(0.f,bounds().width-head);if(!hint_.empty()){y+=kGap;RectF b{x,y,w,hs.lineHeight};c.drawText(hint_,x,c.centeredTextBottom(hint_,b,hs.size,hs.weight),hs.size,enabled_?t.colors.neutralForeground3:t.colors.neutralForegroundDisabled,hs.weight,hs.family);y+=hs.lineHeight;}if(!validationMessage_.empty()){y+=kGap;RectF b{x,y,w,hs.lineHeight};c.drawText(validationMessage_,x,c.centeredTextBottom(validationMessage_,b,hs.size,hs.weight),hs.size,validation(validationState_,t),hs.weight,hs.family);}ContainerNode::paint(c);clearDirty(DirtyFlag::Paint);}

MessageBar::MessageBar(std::string v):body_(std::move(v)){} MessageBar& MessageBar::title(std::string v){setTitle(std::move(v));return *this;}void MessageBar::setTitle(std::string v){if(title_!=v){title_=std::move(v);markDirty(DirtyFlag::Layout);}}const std::string& MessageBar::title()const noexcept{return title_;}MessageBar& MessageBar::body(std::string v){setBody(std::move(v));return *this;}void MessageBar::setBody(std::string v){if(body_!=v){body_=std::move(v);markDirty(DirtyFlag::Layout);}}const std::string& MessageBar::body()const noexcept{return body_;}MessageBar& MessageBar::intent(MessageBarIntent v)noexcept{setIntent(v);return *this;}void MessageBar::setIntent(MessageBarIntent v)noexcept{if(intent_!=v){intent_=v;markDirty(DirtyFlag::Paint);}}MessageBarIntent MessageBar::intent()const noexcept{return intent_;}MessageBar& MessageBar::multiline(bool v)noexcept{setMultiline(v);return *this;}void MessageBar::setMultiline(bool v)noexcept{if(multiline_!=v){multiline_=v;markDirty(DirtyFlag::Layout);}}bool MessageBar::isMultiline()const noexcept{return multiline_;}
MessageBar& MessageBar::addAction(MessageBarAction v){actions_.push_back(std::move(v));markDirty(DirtyFlag::Layout);return *this;}MessageBar& MessageBar::clearActions(){actions_.clear();markDirty(DirtyFlag::Layout);return *this;}const std::vector<MessageBarAction>& MessageBar::actions()const noexcept{return actions_;}MessageBar& MessageBar::dismissible(bool v)noexcept{setDismissible(v);return *this;}void MessageBar::setDismissible(bool v)noexcept{if(dismissible_!=v){dismissible_=v;markDirty(DirtyFlag::Layout);}}bool MessageBar::isDismissible()const noexcept{return dismissible_;}MessageBar& MessageBar::onDismiss(DismissHandler h){onDismiss_=std::move(h);return *this;}
SizeF MessageBar::measure(const Constraints& c)const{const auto&t=theme();const float chrome=kPad*2+kIcon+kMsgGap+(dismissible_?kActionH+kMsgGap:0)+actions_.size()*kActionW;const float available=std::max(1.f,c.maxWidth-chrome);const std::size_t lines=multiline_?std::max<std::size_t>(1,std::size_t(std::ceil(widthOf(body_,t.typography.body1)/available))):1;const float text=(title_.empty()?0:t.typography.body1Strong.lineHeight)+(title_.empty()||body_.empty()?0:2)+lines*t.typography.body1.lineHeight;return c.clamp({chrome+std::max(widthOf(title_,t.typography.body1Strong),widthOf(body_,t.typography.body1)),kPad*2+std::max(kIcon,text)});}void MessageBar::layout(const RectF& b){Node::layout(b);clearLayoutDirtyRecursively();}
RectF MessageBar::dismissBounds()const noexcept{return {bounds().x+bounds().width-kPad-kActionH,bounds().y+kPad,kActionH,kActionH};}RectF MessageBar::actionBounds(std::size_t i)const noexcept{const float r=bounds().x+bounds().width-kPad-(dismissible_?kActionH+kMsgGap:0);return {r-kActionW*float(actions_.size()-i),bounds().y+bounds().height-kPad-kActionH,kActionW,kActionH};}
void MessageBar::paint(PaintContext& c){const auto&t=theme();const Color a=accent(intent_,t);c.fillRoundRect(bounds(),t.radius.medium,messageBg(intent_));c.fillRoundRect({bounds().x,bounds().y,4,bounds().height},t.radius.medium,a);RectF icon{bounds().x+kPad,bounds().y+kPad,kIcon,kIcon};c.fillRoundRect(icon,t.radius.circular,a);c.drawText(intent_==MessageBarIntent::Info?"i":"!",icon.x+7,c.centeredTextBottom("i",icon,t.typography.caption1Strong.size,t.typography.caption1Strong.weight),t.typography.caption1Strong.size,t.colors.onBrand,t.typography.caption1Strong.weight,t.typography.caption1Strong.family);const float right=kPad+(dismissible_?kActionH+kMsgGap:0)+actions_.size()*kActionW;RectF content{icon.x+kIcon+kMsgGap,bounds().y+kPad,std::max(0.f,bounds().width-(icon.x+kIcon+kMsgGap-bounds().x)-right),bounds().height-kPad*2};float y=content.y;if(!title_.empty()){RectF b{content.x,y,content.width,t.typography.body1Strong.lineHeight};c.drawText(title_,b.x,c.centeredTextBottom(title_,b,t.typography.body1Strong.size,t.typography.body1Strong.weight),t.typography.body1Strong.size,t.colors.neutralForeground1,t.typography.body1Strong.weight,t.typography.body1Strong.family);y+=b.height+2;}if(!body_.empty()){RectF b{content.x,y,content.width,t.typography.body1.lineHeight};c.drawText(body_,b.x,c.centeredTextBottom(body_,b,t.typography.body1.size,t.typography.body1.weight),t.typography.body1.size,t.colors.neutralForeground1,t.typography.body1.weight,t.typography.body1.family);}for(std::size_t i=0;i<actions_.size();++i){auto b=actionBounds(i);c.fillRoundRect(b,t.radius.small,t.colors.neutralBackground1.rest);c.drawText(actions_[i].label,b.x+(b.width-widthOf(actions_[i].label,t.typography.caption1Strong))/2,c.centeredTextBottom(actions_[i].label,b,t.typography.caption1Strong.size,t.typography.caption1Strong.weight),t.typography.caption1Strong.size,t.colors.brandForeground1,t.typography.caption1Strong.weight,t.typography.caption1Strong.family);}if(dismissible_){auto b=dismissBounds();c.drawText("×",b.x+7,c.centeredTextBottom("×",b,t.typography.body1Strong.size,t.typography.body1Strong.weight),t.typography.body1Strong.size,t.colors.neutralForeground1,t.typography.body1Strong.weight,t.typography.body1Strong.family);}clearDirty(DirtyFlag::Paint);}
bool MessageBar::onPointerEvent(const PointerEvent&e){if(!isEnabled())return false;if(e.action==PointerAction::Down&&e.button==MouseButton::Left){setVisualState(ControlVisualState::Pressed,true);return true;}if(e.action==PointerAction::Up&&e.button==MouseButton::Left){const bool p=(visualStates()&toMask(ControlVisualState::Pressed))!=0;setVisualState(ControlVisualState::Pressed,false);if(!p)return false;if(dismissible_&&dismissBounds().contains(e.position)){dismiss();return true;}for(std::size_t i=0;i<actions_.size();++i)if(actionBounds(i).contains(e.position)){if(actions_[i].onInvoke)actions_[i].onInvoke();return true;}return true;}if(e.action==PointerAction::Enter){setVisualState(ControlVisualState::Hovered,true);return true;}if(e.action==PointerAction::Leave||e.action==PointerAction::Cancel){setVisualState(ControlVisualState::Hovered,false);setVisualState(ControlVisualState::Pressed,false);return true;}return false;}bool MessageBar::onKeyEvent(const KeyEvent&e){if(isEnabled()&&dismissible_&&e.action==KeyAction::Down&&e.keyCode==27){dismiss();return true;}return false;}AccessibilityActionCapabilities MessageBar::accessibilityActions()const noexcept{AccessibilityActionCapabilities a;a.invoke=dismissible_;return a;}AccessibilityActionStatus MessageBar::performAccessibilityAction(AccessibilityActionKind k,std::string_view){if(k!=AccessibilityActionKind::Invoke||!dismissible_)return AccessibilityActionStatus::NotSupported;if(!isEnabled())return AccessibilityActionStatus::ElementNotEnabled;dismiss();return AccessibilityActionStatus::Succeeded;}void MessageBar::dismiss(){if(onDismiss_)onDismiss_();}
} // namespace wui
